#!/bin/bash
# Start the OBIO backend with env vars from the VPS environment
# Set these in /root/.bashrc or /etc/environment:
#   export RESEND_API_KEY=...
#   export RESEND_FROM_EMAIL='OBIO <admin@obiomacare.com>'
#   export OPENAI_API_KEY=...
#   export STRIPE_SECRET_KEY=...
#   export STRIPE_WEBHOOK_SECRET=...

cd /root/.openclaw/workspace
exec /usr/bin/python3 -m uvicorn masterygraph_api:app --host 0.0.0.0 --port 8000
